### ISSUE TITLE
Lab Descriptions Not Complete

### ISSUE THREAD

**Issue by Link07109** [theChl03/AP-Physics-1-#3]
The Pendulum, Hooke's Law, Wavelength of Sound, Sticky Tape, and Circuits lab are blank in `labsandrelevantcalculations.md`

**Comment by theChl03** [comment]
excuse me sir get out

**Comment by Link07109** [comment]
excuse me ma'am, i need these labs to help me study, and i can't do that if they're not there

so i would appreciate it if you could fix this glaring issue asap.

**Comment by theChl03** [comment]
no *u*

**Comment by Link07109** [comment]
ok
ill clone the repo, fix the issue, and send a pr
